--- #YAML:1.0
name:               Music-Tag-File
version:            0.4101
abstract:           Plugin module for Music::Tag to get information from filename and directory entries. 
author:
    - Edward Allen (ealleniii _at_ cpan _dot_ org)
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    File::Copy:  0
    File::Spec:  3.24
    Music::Tag:  0.4101
    Test::More:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
